# Generated by Django 3.2.4 on 2021-06-27 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='edad',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono_del_tutor',
            field=models.CharField(max_length=10),
        ),
    ]
