# Generated by Django 3.2.4 on 2021-06-27 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210627_1238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='fecha_de_inscripción',
            new_name='fecha_de_inscripcion',
        ),
    ]
